# .github/ISSUE_TEMPLATE/bug_report.yml
name: "🐛 Bug Report"
description: Report a bug to help us improve Dockhand
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out all fields below.

  - type: dropdown
    id: version
    attributes:
      label: "Dockhand Version"
      description: "Check with `docker inspect fnsys/dockhand`"
      options:
        - latest
        - v1.0.6
        - v1.0.5  
        - v1.0.4
        - other
      validations:
        required: true

  - type: dropdown
    id: architecture
    attributes:
      label: "Architecture"
      description: "Check with `uname -m` or `docker info | grep Architecture`"
      options:
        - linux/amd64
        - linux/arm64
        - other
      validations:
        required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "OS, Docker version, deployment method"
      placeholder: |
        Host: Ubuntu 22.04 x86_64
        Docker: 29.1.3
        Deploy: docker compose up -d
      render: shell
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps To Reproduce"
      description: "Exact steps to trigger the bug"
      placeholder: |
        1. docker compose up -d
        2. Open http://localhost:3000
        3. Click 'New Stack'
        4. Paste compose file
        5. Click 'Deploy'
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      placeholder: "What should happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      placeholder: "What actually happens?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs / Error Messages"
      description: "`docker logs dockhand` output"
      render: shell
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots (if UI issue)"
      placeholder: "Drag & drop or paste URLs"

  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      placeholder: "Compose file? Related GitHub issues?"
