name: "🐛 Bug Report"
description: "Report a bug in Dockhand"
type: "Bug"
labels: ["bug"]
body:
  - type: dropdown
    id: version
    attributes:
      label: "Dockhand Version"
      options:
        - latest
        - v1.0.6
        - v1.0.5
        - v1.0.4
        - Other

  - type: dropdown
    id: arch
    attributes:
      label: "Architecture"
      options:
        - linux/amd64
        - linux/arm64

  - type: textarea
    id: steps
    attributes:
      label: "What's happening?"
      description: "Describe the problem"
    validations:
      required: true
