name: "🚀 Feature Request"
description: "Suggest an improvement for Dockhand"
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Feature title"
    validations:
      required: true

