name: "🚀 Feature Request"
description: "Suggest improvements"
body:
  - type: textarea
    id: summary
    attributes:
      label: "Feature title"
      placeholder: "Live container metrics dashboard"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "Use case & motivation"
      placeholder: |
        Current: docker stats - manual refresh
        Wanted: Real-time CPU/RAM graphs per stack
        Priority: High for homelab users
