name: "🚀 Feature Request"
description: "Suggest an improvement for Dockhand"
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Feature title"
      placeholder: ""
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "Use case & motivation"
      placeholder: ""
