name: "💬 Question"
description: "Ask a question about Dockhand"
body:
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      placeholder: "What specifically do you need help with?"
    validations:
      required: true
